### PR TITLE
[IMP] Add possibility to add custom addons_path in a yaml file

### PR DESCRIPTION
**Pull request by dariodelzozzo**

### CODE REVIEW

**Comment by OpenCode** [comment]
@warp10 @dariodelzozzo I have a propose. We can create a file called something like `rocco_extend.yml` or similar where we can add all the extra configuration a user can personalize in the local copy. We can move the extra addons logics in this file. Every new extension can be insert in this new file so we have an unique point to collect personalization. What do you think?

**Comment by dariodelzozzo** [comment]
> @warp10 @dariodelzozzo I have a propose. We can create a file called something like `rocco_extend.yml` or similar where we can add all the extra configuration a user can personalize in the local copy. We can move the extra addons logics in this file. Every new extension can be insert in this new file so we have an unique point to collect personalization. What do you think?

It's the purpose of `extra_addons_path.yaml`.
There you can add every addons_path that you add from external volumes or by git clone inside Dockerfile.

Inside `addons_path_generator.py` it will checks if the yaml file has some extra addons to be inserted inside the conf file.
Is not the same scenario that you describe?

**Comment by dariodelzozzo** [comment]
@OpenCode Changed the file name with a more generic one

**Review by OpenCode — APPROVED** [review]

**Comment by dariodelzozzo** [comment]
@OpenCode yesterday i talk with @warp10 and he would like to manage everything inside the existing file etc/odoo.conf:
https://github.com/saydigital/rocco/blob/master/%7B%7Bcookiecutter.github_repo_name%7D%7D/etc/odoo.conf

instaed of creating a new yaml file.

**Comment by OpenCode** [comment]
> @OpenCode yesterday i talk with @warp10 and he would like to manage everything inside the existing file etc/odoo.conf: https://github.com/saydigital/rocco/blob/master/%7B%7Bcookiecutter.github_repo_name%7D%7D/etc/odoo.conf
> 
> instaed of creating a new yaml file.

But `odoo.conf` is the configuration file Odoo. We are talking about a generic file to change Rocco's specific behavior here.

**Comment by warp10** [comment]
> > @OpenCode yesterday i talk with @warp10 and he would like to manage everything inside the existing file etc/odoo.conf: https://github.com/saydigital/rocco/blob/master/%7B%7Bcookiecutter.github_repo_name%7D%7D/etc/odoo.conf
> > instaed of creating a new yaml file.
> 
> But `odoo.conf` is the configuration file Odoo. We are talking about a generic file to change Rocco's specific behavior here.

Rocco creates the odoo conffile starting from a custom yaml file. We can use that one and centralize our customizations there rather than splitting into two different files

**Comment by OpenCode** [comment]
> > > @OpenCode yesterday i talk with @warp10 and he would like to manage everything inside the existing file etc/odoo.conf: https://github.com/saydigital/rocco/blob/master/%7B%7Bcookiecutter.github_repo_name%7D%7D/etc/odoo.conf
> > > instaed of creating a new yaml file.
> > 
> > 
> > But `odoo.conf` is the configuration file Odoo. We are talking about a generic file to change Rocco's specific behavior here.
> 
> Rocco creates the odoo conffile starting from a custom yaml file. We can use that one and centralize our customizations there rather than splitting into two different files

Where is this yaml file?

**Pull request merged**
